import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <div className="flex min-h-screen w-full">
            <AppSidebar />
            
            {/* O main precisa de flex-1 para empurrar a sidebar para o lado */}
            <main className="flex-1 flex flex-col">
              
              {/* O HEADER termina aqui. Ele é só a barra do topo */}
              <header className="h-14 border-b flex items-center px-4 gap-2 bg-sidebar">
                <SidebarTrigger />
                <h1 className="text-sm font-medium text-muted-foreground">
                  Painel Administrativo
                </h1>
              </header>

              {/* O CONTEÚDO (children) fica FORA do header, em sua própria div */}
              <div className="flex-1 p-6">
                {children}
              </div>

            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
